# Generated by Django 3.0.7 on 2020-06-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200621_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
